### ISSUE TITLE
why not just use python?

### ISSUE THREAD

**Issue by bmaeser** [hintjens/zs#1]
why reinvent the wheel?

python is extreamly readable, people with no python experience can read and understand python code.
multiprocess and multithreading support. it got good really good at concurrency with [asycio/tulip](https://docs.python.org/3/library/asyncio.html) and then there are the good old gevent/enventlet coroutine based libraries,

secure and very well maintained. plays nice with [c](https://docs.python.org/3.4/c-api/),has a interactive shell and there is even a [actor model lib](https://www.pykka.org/en/latest/) out there.

**Comment by hintjens** [comment]
That would offend the majority of developers who do not use python.
