### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [hintjens/zs#2]
Would you like to add more error handling for return values from functions like the following?
- [puts](http://pubs.opengroup.org/onlinepubs/9699919799/functions/puts.html "Put a string on standard output.") ⇒ [main](https://github.com/hintjens/zs/blob/2a6688cddce0143148e1abb7f9de1426d206761e/zs.c#L5)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [s_atomic_new](https://github.com/hintjens/zs/blob/db5a9cf969922266ecc40e827210b82c4ecda0a9/zs_vm.c#L77)

**Comment by hintjens** [comment]
What problem are you encountering?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by hintjens** [comment]
Thanks for your suggestions.
